{%set name = "qds-sdk" %}
{%set snakename = "qds_sdk" %}
{%set version = "1.9.7" %}
{%set hash_type = "sha256" %}
{%set hash_val = "655272df5b932b23d86abf1adad2112878fdd74e81aa53be242939a24db760e1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ snakename }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=1.0.3
    - boto >=2.1.1
    - six >=1.2.0
    - urllib3 >=1.0.2
    - inflection >=0.3.1

test:
  imports:
    - qds_sdk

about:
  home: https://github.com/qubole/qds-sdk-py
  license: Apache 2.0
  summary: 'Python SDK for coding to the Qubole Data Service API'

extra:
  recipe-maintainers:
    - pmlandwehr
