travis:
  secure:
    BINSTAR_TOKEN: E7z9lnsxWllsPM+cll7BEN12k2AU+ItcxGRltUn8hJ+3NxkX1OX/Cd3XHbmC0oZzgKBUATeOXEe0L7nsbbFFTOfDw7+UpzkTQMeUhcD0yRFwKs8v/C7fME30q6ReqS1vVDQDT1Z3zh5bxolGTYFCYdbaT+zs94Z1UZ+P8QPAc9wV7u/dDDJAq5JL4EuKrKiLCf7irmclBGSKH4zyyDeQWs+Vw3aB/G8cPVChPEQUWf4IwtZg5VQJlnMcEOX2eo1geBvIyTuFJIHvbXpr8ANRIyXjvAoYIr2+XREOVQzZRgAOB23Ich5MWl2OhAa5NCDZT5u7CxVP+I1iB2n6DjPOu/UZDDoiVOmbvN6PPzNB7jLNsrUqIvNToTm8Jwd1z8kmWMPrOJnwcUeO0Yw0uJpPh1LgIBhBirtEDzBwNwNZPP0nZ5hpuBN+ap3usVXi2P4VgIOjvs3+1s3hEZZzN4rcnenJ/GQzIh4ovkQG4CD7vf16HoYJHFWR18qFgxh1Pvfj+Q5LDEC7tPi/gA+ALcbXMCKtj/uHQYjAuXgHmROPNJx5C0p4KanrQPfLzmyeUiaf7OSOV+c3PweqR2yMp541ZXDbrnB9ym0uRzyxslOBM9yYZoK9Dmler9YvrOrn7L16gwB+J81C4QNmUzqKu5P+9fEIIs8jPQIo2jGdavhQBk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
