travis:
  secure:
    BINSTAR_TOKEN: ZsqIpM2pqXvxUOQedcnI3GoXdHeuzaYg/J+/XVEJ/oCA5nzxBc/iAnIQTzMGoawcB6Hcreo6Ox71ZywQW/QPc34KJSspRDdFcWCv4iDkHfk8jleRSH8LtI46+3A7gjUUyLEXwesRifCRQc32ZszOl6hB0Oje3LAg4caw2qksoY+9kBXG28ZZobFbblulRcwCjewqlPv/iKGorwliz/RYmBgxBy93KUpTWH8Jt3ykWd2WONA5huvXjgPikRmSnZoLLxbWZVUkon3O4xa+lfcHC63I+RuZ6Rs04fDzUE9b0VLo6z4wAeS8ChXCffP4Pz3VhfB6qSKhk77kd4lnGWmSwsWDd1LsIIhNQDCHu27UVP9IOW0kGwtlufPV6R584J5CIbOD/HMGXX0Zt+xE/0GRM9+TazSwLC4f7RJHWh/nK+N2XrLbya/GWYO30xZPmz6NxfK8ih08Pk1GbCp3mOvWyzisRjIQFFYA4I9WwXvvbfMdzqPGp0zQfwmWeeOQ2q+e2j7zWpsTYtwdKDdi/3lBOugftNfXLjvphtSp0lKZUcmtshS/S5H0HvOkNjkNEcWedr6G1P3ZeSoDJgv+uvh0awgBq0OcH7M6VqpQXvikQzwPClWY2JsktbhmCnVIAORDa9rdyqKP5J2CHv6l2RTDNONEfWz5IBg0QMat0gkf/8w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
