travis:
  secure:
    BINSTAR_TOKEN: okz6Mj9lLOoo/1e6byR+IPPbUihZAEGYrlHa6Yl2uxiQaZ82Q0lTUmPfxoEkhdyrOPN4PnwnxOpX70rBudK4U4uv5yWnKEpdESiJMlifHMxo8deHjeac/rDL0naDpHJx74VtILK2FI0jO2Fv83ziSmZpOpnoLcZL9vsaU9fzRBXwr+jpfvgFRu+3QiJylOU4T6KUVvii0rhFASqDEgM4DgRn+dTtAz6oy9ji/aC1MFCf+zFlCO+xNBVL3YaluXk1wnV1FFFYc+f8FGjMyIoCkw7Rn3lQPXOCowr0cNlYv3kBol8wUMXHYE9l/AM7Q1K3YhNbHqCM3sRyV6UkedMA0JRaEvXw0Q4HEHV0pkmMsQIxvOIXYBBr1A0t7p4oXN7y+HL+VgzSqB7CP8kMI2RehdX9/CtLwhv51c8FKsR247HpjjLT/MhYX/33YoRl3YaHFYFbqn8Zb/dAwcJOgGJd5HqevcRHqgZUoUsH1m53rETQKiFR9IjGgf9BAIdNnntp83ZuXJNksEVA0NnCaazvvGbG1u/DWsiPfXwRsr4Eew40uC7PDgvSXP/Ui7VzFwjQDSEuzn4bAQ8LA8rE8AFxI+UjPk+kmqv//RlAqG7WYl0bHUKQtz5UDy/gSb/uL26Ry50SHsDoczibJaq9rK/t7qG4QWwz7NEDhLiRNDbCdFI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
